### Octave/Matlab example:

**Input**
```
% Initialize matrix A and B 
A = [1, 2, 4; 5, 3, 2]
B = [1, 3, 4; 1, 1, 1]

% Initialize constant s 
s = 2

% See how element-wise addition works
add_AB = A + B 

% See how element-wise subtraction works
sub_AB = A - B

% See how scalar multiplication works
mult_As = A * s

% Divide A by s
div_As = A / s

% What happens if we have a Matrix + scalar?
add_As = A + s
```

**Output**
```
A =

   1   2   4
   5   3   2

B =

   1   3   4
   1   1   1

s =  2
add_AB =

   2   5   8
   6   4   3

sub_AB =

   0  -1   0
   4   2   1

mult_As =

    2    4    8
   10    6    4

div_As =

   0.50000   1.00000   2.00000
   2.50000   1.50000   1.00000

add_As =

   3   4   6
   7   5   4
```

### I'm going to do it in python/numpy:

In [1]:
import numpy as np

A = np.array([[1,2,4],[5,3,2]])
B = np.array([[1,3,4],[1,1,1]])
s = 2

In [2]:
A+B

array([[2, 5, 8],
       [6, 4, 3]])

In [3]:
A-B

array([[ 0, -1,  0],
       [ 4,  2,  1]])

In [4]:
A*s

array([[ 2,  4,  8],
       [10,  6,  4]])

In [5]:
A/s

array([[ 0.5,  1. ,  2. ],
       [ 2.5,  1.5,  1. ]])

In [6]:
A+s

array([[3, 4, 6],
       [7, 5, 4]])