### Octave/Matlab example:

**Input**
```
% Initialize matrix A 
A = [1,2,0;0,5,6;7,0,9]

% Transpose A 
A_trans = A' 

% Take the inverse of A 
A_inv = inv(A)

% What is A^(-1)*A? 
A_invA = inv(A)*A
```
**Output**
```
A =

   1   2   0
   0   5   6
   7   0   9

A_trans =

   1   0   7
   2   5   0
   0   6   9

A_inv =

   0.348837  -0.139535   0.093023
   0.325581   0.069767  -0.046512
  -0.271318   0.108527   0.038760

A_invA =

   1.00000  -0.00000   0.00000
   0.00000   1.00000  -0.00000
  -0.00000   0.00000   1.00000
```

### I'm going to do it in python/numpy:

In [8]:
import numpy as np

A = np.array([[1,2,0],[0,5,6],[7,0,9]])
A

array([[1, 2, 0],
       [0, 5, 6],
       [7, 0, 9]])

In [9]:
A.transpose()

array([[1, 0, 7],
       [2, 5, 0],
       [0, 6, 9]])

In [17]:
from numpy.linalg import inv
invA = inv(A)
invA

array([[ 0.34883721, -0.13953488,  0.09302326],
       [ 0.3255814 ,  0.06976744, -0.04651163],
       [-0.27131783,  0.10852713,  0.03875969]])

In [19]:
np.dot(invA, A)

array([[  1.00000000e+00,   0.00000000e+00,   1.80411242e-16],
       [  2.08166817e-17,   1.00000000e+00,   3.46944695e-17],
       [ -3.46944695e-17,   0.00000000e+00,   1.00000000e+00]])