### Octave/Matlab example:
**Input**
```
% Initialize random matrices A and B 
A = [1,2;4,5]
B = [1,1;0,2]

% Initialize a 2 by 2 identity matrix
I = eye(2)

% The above notation is the same as I = [1,0;0,1]

% What happens when we multiply I*A ? 
IA = I*A 

% How about A*I ? 
AI = A*I 

% Compute A*B 
AB = A*B 

% Is it equal to B*A? 
BA = B*A 
```
**Output**
```
A =

   1   2
   4   5

B =

   1   1
   0   2

I =

Diagonal Matrix

   1   0
   0   1

IA =

   1   2
   4   5

AI =

   1   2
   4   5

AB =

    1    5
    4   14

BA =

    5    7
    8   10
```

### I'm going to do it in python/numpy:

In [3]:
import numpy as np

A = np.array([[1,2],[4,5]])
A

array([[1, 2],
       [4, 5]])

In [4]:
B = np.array([[1,1],[0,2]])
B

array([[1, 1],
       [0, 2]])

In [5]:
I = np.identity(2)
I

array([[ 1.,  0.],
       [ 0.,  1.]])

In [10]:
np.dot(I,A)

array([[ 1.,  2.],
       [ 4.,  5.]])

In [11]:
np.dot(A,I)

array([[ 1.,  2.],
       [ 4.,  5.]])

In [12]:
np.dot(A,B)

array([[ 1,  5],
       [ 4, 14]])

In [13]:
np.dot(B,A)

array([[ 5,  7],
       [ 8, 10]])