### Octave/Matlab example:

**Input**
```
% The ; denotes we are going back to a new row.
A = [1, 2, 3; 4, 5, 6; 7, 8, 9; 10, 11, 12]

% Initialize a vector 
v = [1;2;3] 

% Get the dimension of the matrix A where m = rows and n = columns
[m,n] = size(A)

% You could also store it this way
dim_A = size(A)

% Get the dimension of the vector v 
dim_v = size(v)

% Now let's index into the 2nd row 3rd column of matrix A
A_23 = A(2,3)
```

**Output**
```
A =

    1    2    3
    4    5    6
    7    8    9
   10   11   12

v =

   1
   2
   3

m =  4
n =  3
dim_A =

   4   3

dim_v =

   3   1

A_23 =  6
```

### I'm going to do it in python/numpy:

In [2]:
import numpy as np

In [18]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
v = np.array([1,2,3])

In [11]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
v

array([1, 2, 3])

In [14]:
m, n = A.shape
print(m, n)

3 3


In [15]:
A.shape

(3, 3)

In [16]:
v.shape

(3,)

In [17]:
A[1,2] #numpy uses zero-indexing

6